% create_table_gsflowcsv.m
% Create table of gsflow-csv-file variables

% see Table 12 of GSFLOW manual

% Create cell with descriptions
gsflow_csv_data.varname = cell(50,1);
gsflow_csv_data.unit = cell(50,1);
gsflow_csv_data.descr = cell(50,1);

MODFLOW_len_unit = 'm'; 
MODFLOW_time_unit = 'd'; % should be day

ii = 0;
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'Date';
gsflow_csv_data.descr{ii} = 'Date Month, day, and year designation';
gsflow_csv_data.unit{ii} = 'Mon/Day/Yr';

ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinppt'; % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of precipitation on modeled region';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];

ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinpervet'; 
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of evapotranspiration from pervious areas'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinimpervevap '; 
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of evaporation from impervious areas'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinintcpevap'; 
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of evaporation of intercepted precipitation'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinsnowevap'; 
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of snowpack sublimation'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinstrmflow'; % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of streamflow leaving modeled region'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinsz2gw'; 
gsflow_csv_data.descr{ii} = 'Potential volumetric flow rate of gravity drainage from the soil zone to the unsaturated zone (before conditions of the unsaturated and saturated zones are applied)'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basingw2sz'; % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of ground-water discharge from the saturated zone to the soil zone'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'gw_inout'; % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate to saturated zone along external boundary (negative value is flow out of modeled region)'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'stream_leakage';  % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of stream leakage to the unsaturated and saturated zones'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'uzf_recharge'; 
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of recharge from the unsaturated zone to the saturated zone'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinseepout'; % **** (same as basingw2sz)
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of ground-water discharge from the saturated zone to the soil zone'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'sat_stor'; 
gsflow_csv_data.descr{ii} = 'Volume of water in the saturated zone'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3'];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'unsat_stor'; 
gsflow_csv_data.descr{ii} = 'Volume of water in the unsaturated zone'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3'];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinsoilmoist'; 
gsflow_csv_data.descr{ii} = 'Volume of water in capillary reservoirs of the soil zone'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3'];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basingravstor'; 
gsflow_csv_data.descr{ii} = 'Volume of water in gravity reservoirs of the soil zone'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3'];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basingwstor'; 
gsflow_csv_data.descr{ii} = 'Volume of water in PRMS ground-water reservoirs (PRMS-only simulation)'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3'];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinintcpstor'; 
gsflow_csv_data.descr{ii} = 'Volume of intercepted precipitation in plant-canopy reservoirs'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3'];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinimpervstor';
gsflow_csv_data.descr{ii} = 'Volume of water in impervious reservoir'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3'];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinpweqv'; 
gsflow_csv_data.descr{ii} = 'Volume of water in snowpack storage'; 
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3'];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basininterflow'; % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of slow interflow to streams';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinsroff'; % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of the sum of Hortonian (Horton, 1933) and Dunnian surface runoff (Dunne and Black, 1970) to streams';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'strm_stor';
gsflow_csv_data.descr{ii} = 'Volume of water in streams';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3'];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'lake_stor';
gsflow_csv_data.descr{ii} = 'Volume of water in lakes';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3'];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'obs_strmflow';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of streamflow measured at a gaging station';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinszreject';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of gravity drainage from the soil zone not accepted due to the conditions in the unsaturated and saturated zones';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinprefstor';
gsflow_csv_data.descr{ii} = 'Volume of water stores in preferential-flow reservoirs of the soil zone';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3']; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'uzf_et';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of evapotranspiration from the unsaturated and saturated zones';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'uzf_infil'; % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of gravity drainage to the unsaturated and saturated zones';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'uzf_del_stor';
gsflow_csv_data.descr{ii} = 'Change in unsaturated-zone storage';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3']; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'net_sz2gw'; % ****
gsflow_csv_data.descr{ii} = 'Net volumetric flow rate of gravity drainage from the soilzone to the unsaturated and saturated zones';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'sat_change_stor';
gsflow_csv_data.descr{ii} = 'Change in saturated-zone storage';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3']; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'streambed_loss'; % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of stream leakage to unsaturated and saturated zones';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'sfruz_change_store';
gsflow_csv_data.descr{ii} = 'Change in unsaturated-zone storage under streams';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3']; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'gwflow2strms'; % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of ground-water discharge to streams';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'sfruz_tot_stor';
gsflow_csv_data.descr{ii} = 'Volume of water in the unsaturated zone';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3']; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'lakebed_loss';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of lake leakage to the unsaturated and saturated zones';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'lake_change_stor'; 
gsflow_csv_data.descr{ii} = 'Change in lake storage';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3']; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'gwflow2lakes';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of ground-water discharge to lakes';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit];  
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basininfil'; % **** (vs. uz_infil: this one is before ET?)
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of soil infiltration including precipitation, snowmelt, and cascading Hortonian flow';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basindunnian';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of Dunnian runoff to streams';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinhortonian';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of Hortonian runoff to streams';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinsm2gvr';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of flow from capillary reservoirs to gravity reservoirs';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basingvr2sm';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of replenishment of capillary reservoirs from gravity reservoirs';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basininfil_tot'; 
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of soil infiltration into capillary reservoirs including precipitation, snowmelt, and cascading Hortonian and Dunnian runoff and interflow minus infiltration to preferential-flow reservoirs';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basininfil2pref';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of soil infiltration into preferential-flow reservoirs including precipitation, snowmelt, and cascading surface runoff';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basindnflow';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of cascading Dunnian runoff and interflow to HRUs';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinactet'; % ****
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of actual evapotranspiration from HRUs';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinsnowmelt';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of snowmelt';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinhortonianlakes';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of Hortonian runoff to lakes';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinlakeinsz';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of Dunnian runoff and interflow to lakes';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinlakeevap';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of evaporation from lakes';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'basinlakeprecip';
gsflow_csv_data.descr{ii} = 'Volumetric flow rate of precipitation on lakes';
gsflow_csv_data.unit{ii} = [MODFLOW_len_unit, '^3/', MODFLOW_time_unit]; 
ii = ii+1; 
gsflow_csv_data.varname{ii} = 'kkiter';
gsflow_csv_data.descr{ii} = 'Number of iterations for each time step';
gsflow_csv_data.unit{ii} = 'none';



