#! /bin/bash

set -x
set -o errexit
cd $HOME
echo "" | grass74 -c EPSG:2100 /home/mezcla/grassdata
git clone https://github.com/UMN-Hydro/GSFLOW-GRASS.git
cd GSFLOW-GRASS

grep -v ^# domain_builder/install_extensions.sh | grass74

